### ISSUE TITLE
nginx反代并301为https访问时, 无法Start Nexttrace

### ISSUE THREAD

**Issue by zuilintan** [nxtrace/nexttracewebapi#15]

**Comment by kernelcrashdump** [comment]
肯定是你配置的问题，这个docker容器是自带nginx的  
你可以参考下配置

**Comment by zuilintan** [comment]
> 肯定是你配置的问题，这个docker容器是自带nginx的 你可以参考下配置

确实如此, 需要添加映射: 
location /socket.io {
    proxy_pass http://localhost:35000/socket.io;
    include /etc/nginx/snippets/proxy-settings.conf;
}
