### ISSUE TITLE
[Feature] 添加socket.io端口 35000 的自定义

### ISSUE THREAD

**Issue by zuilintan** [nxtrace/nexttracewebapi#18]

**Comment by zuilintan** [comment]
如entrypoint.sh `30080 ` 处理方式

**Comment by tsosunchia** [comment]
没懂这样做的目的是啥，本仓库提供修改nginx暴露端口的办法了呀

**Comment by tsosunchia** [comment]
nginx暴露的就是反代socket.io过后的

**Comment by zuilintan** [comment]
是这样的，
首先，/socket.io需要在宿主的nginx中再次反代，并指定35000，
否则无法正常在外网进行路由追踪。

而35000这个端口，有其它程序将占用，冲突。

所以，建议也为其追加其自定义。

**Comment by zuilintan** [comment]
我原打算通过bridge方式部署，
对35000映射，
可惜如此却也无法正常路由追踪了
