### ISSUE TITLE
问一下依据什么来显示的？

### ISSUE THREAD

**Issue by aliuzzz** [nxtrace/nexttracewebapi#5]
![image](https://github.com/nxtrace/nexttracewebapi/assets/43594093/08b849a0-6787-4501-8b52-a892746e680e)
看到支持mtr的loss%输出。hop都是一致的，但是部分hop没有显示出来。这个是根据什么所显示的呢？

**Comment by tsosunchia** [comment]
丢包率比较高的HOP，可能会引起BUG，导致这类HOP无法显示

暂时还没有找到解决的办法
